theme: jekyll-theme-minimal
title: MultiFEBE
description: Multi-domain Finite Element and Boundary Element linear mechanics solver
logo: https://raw.githubusercontent.com/mmc-siani-es/MultiFEBE/main/docs/img/logo.png
show_downloads: true
github:
  zip_url: https://github.com/mmc-siani-es/MultiFEBE
  tar_url: https://github.com/mmc-siani-es/MultiFEBE/releases/tag/v2.0.0
